### ISSUE TITLE
Hello, first of all, thank you so much for your open source. I am very interested in your work.

### ISSUE THREAD

**Issue by thebestYezhang** [adobe-research/diffusion-rig#1]
I have finished the finetuning exm in my personal album flowing your  Redme.md. The result remains good and fantastic! But I have a question: as stated in your paper, the diff-org will be affected by DECA’s limited estimation capability.  So can I replace the DECA part with Deep3D model? Do you have any suggestions for me if I do the replacement?

**Comment by zh-ding** [comment]
Hi, thanks for your interest in our work! Yes, I think that should be feasible. Ideally any model like DECA might work. We choose DECA since it's easy to use and manipulate.

**Comment by QvQKing** [comment]
> Hi, thanks for your interest in our work! Yes, I think that should be feasible. Ideally any model like DECA might work. We choose DECA since it's easy to use and manipulate.

Hi, I encountered this issue while running the project and would like to ask you how to solve it.
creating the FLAME Decoder
trained model found. load /hy-tmp/2023A/DECA/diffusion-rig-main/data/deca_model.tar
/usr/local/miniconda3/envs/diffusionrig1.11/lib/python3.8/site-packages/pytorch3d/io/obj_io.py:546: UserWarning: Mtl file does not exist: /hy-tmp/2023A/DECA/diffusion-rig-main/data/template.mtl
  warnings.warn(f"Mtl file does not exist: {f}")
Traceback (most recent call last):
  File "scripts/create_data.py", line 133, in <module>
    main()
  File "scripts/create_data.py", line 33, in main
    testdata = datasets.TestData(
  File "/hy-tmp/2023A/DECA/diffusion-rig-main/decalib/datasets/datasets.py", line 73, in __init__
    self.face_detector = detectors.FAN()
  File "/hy-tmp/2023A/DECA/diffusion-rig-main/decalib/datasets/detectors.py", line 22, in __init__
    self.model = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=False)
  File "/usr/local/miniconda3/envs/diffusionrig1.11/lib/python3.8/enum.py", line 384, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D

**Comment by sunzhe09** [comment]
I met the sample problem

**Comment by sunzhe09** [comment]
@QvQKing you can fix it according to solution in https://stackoverflow.com/questions/76651887/am-facing-attributeerror2d-how-do-i-resolve-it
