### ISSUE TITLE
running failed

### ISSUE THREAD

**Issue by wzx7084** [adobe-research/diffusion-rig#3]
Traceback (most recent call last):
  File "scripts/create_data.py", line 133, in <module>
    main()
  File "scripts/create_data.py", line 33, in main
    testdata = datasets.TestData(
  File "/home/ncepucce/PycharmProjects/Diffusion-rig/decalib/datasets/datasets.py", line 73, in __init__
    self.face_detector = detectors.FAN()
  File "/home/ncepucce/PycharmProjects/Diffusion-rig/decalib/datasets/detectors.py", line 22, in __init__
    self.model = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D,flip_input=False)
  File "/home/ncepucce/ProgramFiles/anaconda3/envs/diffusionrig/lib/python3.8/enum.py", line 384, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D

I am very interested in your work. If you could tell me where the problem lies, I would be very grateful！

**Comment by QvQKing** [comment]
Have you solved this problem？

**Comment by NickChang97** [comment]
Can you share your solution ? Thans in advance.

**Comment by NickChang97** [comment]
> Have you solved this problem？

you can fix it according to solution in  https://stackoverflow.com/questions/76651887/am-facing-attributeerror2d-how-do-i-resolve-it
